import type { Metadata } from 'next';
import { jost } from '@/app/ui/fonts';
import './globals.css';
import clsx from 'clsx';
import Logo from './ui/logo';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          jost.className,
          'bg-color-surface-mixed-100 text-white'
        )}
      >
        <main>
          <Logo />
          {children}
        </main>
      </body>
    </html>
  );
}
